name: flutter_sport_news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  dio: ^4.0.4 
  get_it: ^7.2.0
  equatable: ^2.0.3
  carrier_info: ^2.0.5
  flutter_bloc: ^7.3.1
  firebase_core: ^1.5.0
  webview_flutter: ^3.0.4
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.0
  transparent_image: ^2.0.0
  shared_preferences: ^2.0.13
  flutter_web_browser: ^0.15.0
  firebase_remote_config: ^2.0.19

#!auto-Mation
  json_serializable: ^6.1.6
  json_annotation: ^4.4.0
  build_runner: ^2.1.10
  auto_route_generator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: any

  flutter_lints: ^1.0.0

flutter:

  
  uses-material-design: true

  