class News {
  String? id;
  String? name;
  String? description;
  String? url;
  String? picture;

  News({
    this.id,
    this.name,
    this.description,
    this.url,
    this.picture
  });
}

List<News> newsList = [
  News(picture: "https://lookcharms.com/wp-content/uploads/2022/05/Sans_titre.jpg", id: "bleacher-report", name: "Bleacher Report", description: "Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!", url: "http://www.bleacherreport.com"),
  News(picture: "https://artwork.espncdn.com/categories/0f8e3d42-fa27-3f60-9e8d-276e4892f50e/1x1Feature/1440_20200909185236.jpg",id: "espn", name: "ESPN", description: "ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.", url:"http://www.bleacherreport.com"),
  News(picture: "https://image3.mouthshut.com/images/imagesp/925738506s.jpg",id: "espn-cric-info", name: "ESPN Cric Info", description: "ESPN Cricinfo provides the most comprehensive cricket coverage available including live ball-by-ball commentary, news, unparalleled statistics, quality editorial comment and analysis.", url: "http://espn.go.com"),
  News(picture: "https://play-lh.googleusercontent.com/6Jaqkn0Ok9ycbZ0TdDTZ9OAaNfQ3v0J8ftP4QQG-MHnUGIej7-5nLBFTREa0i9EgjHM=w240-h480-rw",id: "fox-sports", name: "Fox Sports", description: "Find live scores, player and team news, videos, rumors, stats, standings, schedules and fantasy games on FOX Sports.", url: "http://www.foxsports.com"),
  News(picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXI9deJGqeleMYvV59Al5EQN_ZTXZtAENyIA&usqp=CAU",id: "nfl-news", name: "NFL News", description: "The official source for NFL news, schedules, stats, scores and more.", url: "http://www.nfl.com/news"),
  News(picture: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3a/05_NHL_Shield.svg/1200px-05_NHL_Shield.svg.png",id: "nhl-news", name: "nhl-news", description: "The most up-to-date breaking hockey news from the official source including interviews, rumors, statistics and schedules.", url: "https://www.nhl.com/news"),
  News(picture: "https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt0c18809827fd5cbe/6311c1316ee2d94d6e6a55b6/ONLY_GERMANY_Jordi_Alba_Barcelona_2022.jpg?quality=80&format=pjpg&auto=webp&width=1000", id: "news", name: "Alba linked with Juventus", description: "Barcelona left-back Jordi Alba might end up leaving his boyhood club soon. Calcio Mercato has reported that the 33-year-old might be on the move to Italian heavyweights Juventus.", url: "https://www.goal.com/en/news/live/barcelona-transfer-news-rumours-today/blt71f5148b4b7ad0c6#cs41c877d2844e6960"),
  News(picture: "https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt7e26fa0981c868c5/6322345864bbad3aef9fa796/Ilkay_Gundogan_Manchester_City_Dortmund_2022-23.png?quality=80&format=pjpg&auto=webp&width=1000", id: "news", name: "Barca interested in İlkay Gündoğan", description: "Barcelona are interested in signing Manchester City midfielder İlkay Gündoğan once his contract expires at the end of the season, as per caughtoffside.", url: "https://www.goal.com/en/news/live/barcelona-transfer-news-rumours-today/blt71f5148b4b7ad0c6#csf3d8f6448e3a758c"),
  News(picture: "https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/blt2397c8a7204acb25/60dc67135e51ad3b1d29d31b/0e43d4d1dd2ebd34e5a4931db9db624f68ec1327.jpg?quality=80&format=pjpg&auto=webp&width=1000", id: "news", name: "Barca monitoring Man Utd duo Marcus Rashford and Diogo Dalot", description: "As per Sport, Barcelona are keeping an eye on Marcus Rashford and Diogo Dalot's contract situations at Manchester United. Both players' contracts expire at the end of this season. However, Rashford's contract has a one-year extension option that can be triggered by United.", url: "https://www.goal.com/en/news/live/barcelona-transfer-news-rumours-today/blt71f5148b4b7ad0c6#cs50c77429f4d0b39e"),
  News(picture: "https://assets.goal.com/v3/assets/bltcc7a7ffd2fbf71f5/bltba02594ea7448af3/633862c1d1452921ab940333/Miguel_Almiron_Newcastle_2022-23.jpg?quality=80&format=pjpg&auto=webp&width=1000", id: "news", name: "Newcastle United vs Brentford:", description: "The English top flight continues this weekend - here's everything you need to know", url: "https://www.goal.com/en/news/newcastle-united-vs-brentford-live-stream-tv-channel-kick-off-time-and-how-to-watch/blt872e2ebedec5f5ed"),
  News(picture: "https://cdn.racing.com/-/media/racing/horses/s/soyouthinkstevenarnoldunderwoodstakes_660x380garywild.jpg?h=380&w=660&la=en&hash=C27FFB1C139852F1C5C6494DF6584E8DF30D957E", id: "news", name: "Arnold thinks Anamoe faces challenge", description: "The one to beat but beatable is how former jockey Steven Arnold assesses Godolphin's five-time Group 1 winner Anamoe ahead of Saturday's 1 million-usd Might And Power Stakes (2000m) at Caulfield.\nArnold rode 15 G1 winners between 2003 and 2015 and memorably guided So You Think to four top-level victories in the spring of 2010, including the race formerly known as the Caulfield Stakes.", url: "https://www.racing.com/news/2022-10-07/news-preview-arnold-thinks-anamoe-faces-challenge"),
  News(picture: "https://cdn.racing.com/-/media/racing/generic/barriershorsejump_630x368dmac.jpg?h=368&w=630&la=en&hash=8CA95630DD1D256FFBE1D1F5727F5820812FAACB", id: "news", name: "Lack of trials frustrates trainers", description: "Leading Victorian stables have expressed their frustration at the lack of official trials across the state, fearful their juveniles will be disadvantaged compared to interstate counterparts over the Spring Carnival.", url: "https://www.racing.com/news/2022-10-06/news-industry-lack-of-trials-frustrates-trainers"),
  News(picture: "https://a2.espncdn.com/combiner/i?img=%2Fphoto%2F2022%2F1005%2Fnba_clippers%2D5%2Dquestions_16x9.jpg&w=1140&cquality=40&format=jpg", id: "news", name: "Can Kawhi Leonard regain his dominant form? ", description: "The LA Clippers enter the 2022-23 season -- Year 4 of the Kawhi Leonard-Paul George era -- with enormous expectations. They have a superstar two-way duo. They have perhaps the deepest roster in the league. They are loaded with veteran experience and interchangeable players at almost every position. And they have a master tactician in coach Tyronn Lue to make it all work", url: "https://www.espn.com/nba/story/_/id/34732857/the-biggest-questions-surrounding-la-clippers"),
  News(picture: "https://a4.espncdn.com/combiner/i?img=%2Fphoto%2F2022%2F1006%2Fr1071921_1296x729_16%2D9.jpg&w=1140&cquality=40&format=jpg", id: "news", name: "Is this the year that Leonard and Paul George finally deliver what they went to L.A. for?", description: "George helped organize two offseason minicamp-like outings in San Diego and Santa Barbara and even paid the expenses for some of his younger teammates. Last season, when Leonard didn't play and George was out for three months with an elbow injury, the two traveled with the team at times and would analyze together what the Clippers were doing.", url: "https://www.espn.com/nba/story/_/id/34732857/the-biggest-questions-surrounding-la-clippers"),
  News(picture: "https://cdn.racing.com/-/media/racing/columns-2022/ontheclock-660x380.jpg?h=380&w=660&la=en&hash=90A55A5303424F4BBE78FF1D62A188C6B5C6C279", id: "news", name: "The must-watch races this weekend", description: "Feature racing heads to Caulfield for Guineas Day, with two accompanying Group 1s and an undercard stacked with talent. Racing North of the border is highlighted by the Silver Eagle at Randwick.", url: "https://www.racing.com/news/2022-10-07/ontheclock-71022"),
];
